spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456


logging:
  level:
    org.springframework: DEBUG